const express=require('express')
const { confirmEmail, resendTokenPost, forgotPassword,resendForgotPassword } = require('../controllers/confirmEmail')
const router=express()
const {postUser,userInfo, requireSignin}=require('../controllers/userController')
const {getUser}=require('../controllers/userController')
const {signIn}=require('../controllers/userController')
const {signOut}=require('../controllers/userController')
const {userByid}=require('../controllers/userController')
router.get('/users',getUser)
router.post('/users',postUser)
router.post('/users/signin',signIn)
router.get('/users/signout',signOut)
router.get('/userinfo/:userId',requireSignin,userInfo)
router.param('userId',userByid)
router.post('/confirmation/:userToken',confirmEmail)
router.put('/forgotpassword/:userToken',forgotPassword)
router.post('/resendtoken/',resendTokenPost)
router.post('/resendforgotpassword/',resendForgotPassword)
module.exports=router